#!/usr/bin/python
import sys
import os
import subprocess
import shlex
sys.path.append(os.environ['NVM_PATH'] + '/src/lib')

import data_loader
import colors
import github
import version_manager


if __name__ == '__main__':

	if len(sys.argv) < 2:
		print 'Useage: ' + colors.yellow('nvm-install <tag>')
		exit()

	tag = sys.argv[1]
	data = data_loader.load_data()

	#check to see if its install already
	try:
		data['installed_versions'].index(tag)

		print colors.yellow(tag + " is already installed")
		exit()
	except:
		# not installed
		pass
	
	#check to see if its a valid tag
	if github.is_valid_tag(tag) != True:
		print colors.red(tag + ' is not a valid tag')
		exit()
	
	#install the version
	
	#create the right dir
	#os.system("mkdir " + os.environ['NVM_VERSIONS'] + '/' + tag)
	clone_path = os.environ['NVM_VERSIONS'] + '/' + tag
	
	print colors.green("Cloning node.js to " + clone_path + "...") + "\n"

	clone = "git clone https://github.com/joyent/node " + clone_path
	if(subprocess.call(clone, shell=True) != 0):
		print colors.red("Failed to clone repository")
		exit()	
	
	symlink = ''

	version_manager.set_version(tag, data)

	print colors.green("Checking out tag " + tag + "...") + "\n"

	checkout = "cd " + clone_path + " && git checkout " + tag
	if(subprocess.call(checkout, shell=True) != 0):
		print colors.red("Failed to checkout tag " + tag)
		exit()

	print colors.green("Building Nodejs...") + "\n"

	make = "cd " + clone_path + " && ./configure && make && make install"
	if(subprocess.call(make, shell=True) != 0):
		print colors.red("Failed to configure and make")
		exit()

	data['installed_versions'].append(tag)

	data_loader.save_data(data)
	
